### ISSUE TITLE
 "npm run build" Error

### ISSUE THREAD

**Issue by jhorgint** [sudaraka/udemy-reactive-js#1]
webpack.config.babel.js:1 syntax error: unexpected token import

seems webpack.config.babel.js: not support  ES6

I use require("") instead of import in webpack.config.babel.js but ES6 is not support in the others files too

I have little experience programming could you help me

**Comment by sudaraka** [comment]
Reason for the issue is because `package.json` is missing the `babel-core`
in the dependency list. With that added you should be able to use all
ES2015 features in `webpack.config.babel.js`.

Thanks for reporting the issue.

**Comment by jhorgint** [comment]
I tried it but didn't work, then I changed all my "imports" with require() and finally webpack runs fine

I was reading about the theme but frankly it seems a little tricky therefore I set my webpack config files this way

Thanks a lot for sharing :-)
